import type { ProductItem } from "@/types/product";

export const products: ProductItem[] = [
  {
    id: 1,
    slug: "livestock",
    title: "دام زنده سالم",
    description:
      "عرضه دام سالم و پرورش‌یافته تحت نظارت، مناسب مجموعه‌ها و خریداران عمده.",
    longDescription: [
      "دام‌های مجموعه با رعایت اصول بهداشتی و تحت نظارت تخصصی نگهداری می‌شوند.",
      "قیمت و شرایط عرضه بر اساس نوع دام، نژاد، وزن و تعداد موردنیاز مشخص می‌شود.",
    ],
    category: "دام زنده",
    image: "/images/products/livestock.webp",
    cover: "/images/products/livestock.webp",
    gallery: [
      "/images/products/livestock.webp",
      "/images/activities/livestock.jpg",
      "/images/activities/livestock-cover.jpg",
    ],
    features: ["بررسی سلامت دام", "امکان سفارش عمده", "مشاوره پیش از خرید"],
    purchaseType: "request",
    unit: "رأس",
    isAvailable: true,
    requestFields: {
      quantity: true,
      breed: true,
      approximateWeight: true,
      description: true,
    },
  },
  {
    id: 2,
    slug: "fresh-milk",
    title: "شیر تازه دامداری",
    description: "شیر تازه تولیدشده با رعایت اصول بهداشتی و کنترل مستمر کیفیت.",
    longDescription: [
      "شیر تازه مجموعه به‌صورت روزانه تولید و کنترل کیفی می‌شود.",
      "فرآیند نگهداری و عرضه با رعایت زنجیره بهداشتی انجام می‌شود.",
    ],
    category: "محصولات لبنی",
    image: "/images/products/milk.webp",
    cover: "/images/products/milk.webp",
    gallery: [
      "/images/products/milk.webp",
      "/images/activities/milk.jpg",
      "/images/activities/milk-cover.jpg",
    ],
    features: ["تولید روزانه", "کنترل کیفیت", "عرضه بهداشتی"],
    purchaseType: "direct",
    unit: "لیتر",
    isAvailable: true,
    price: 85000,
    stock: 500,
  },
  {
    id: 3,
    slug: "calves",
    title: "گوساله پرورشی",
    description:
      "گوساله‌های سالم با برنامه تغذیه و مراقبت تخصصی برای پرورش اصولی.",
    longDescription: [
      "گوساله‌ها با برنامه تغذیه و مراقبت منظم پرورش داده می‌شوند.",
      "قیمت نهایی بر اساس سن، نژاد، وزن و تعداد موردنیاز تعیین می‌شود.",
    ],
    category: "پرورش دام",
    image: "/images/products/calf.webp",
    cover: "/images/products/calf.webp",
    gallery: [
      "/images/products/calf.webp",
      "/images/activities/calves.jpg",
      "/images/activities/calves-cover.jpg",
    ],
    features: ["پایش سلامت", "برنامه تغذیه اصولی", "مناسب پرورش تخصصی"],
    purchaseType: "request",
    unit: "رأس",
    isAvailable: true,
    requestFields: {
      quantity: true,
      breed: true,
      approximateWeight: true,
      description: true,
    },
  },
  {
    id: 4,
    slug: "animal-feed",
    title: "خوراک دام",
    description:
      "خوراک استاندارد و متعادل برای رشد، سلامت و بهره‌وری بهتر دام.",
    longDescription: [
      "خوراک دام متناسب با نیازهای تغذیه‌ای و شرایط پرورش تأمین می‌شود.",
      "امکان خرید در حجم‌های مختلف برای دامداری‌ها فراهم است.",
    ],
    category: "خوراک دام",
    image: "/images/activities/feed.jpg",
    cover: "/images/activities/feed-cover.jpg",
    gallery: [
      "/images/activities/feed.jpg",
      "/images/activities/feed-cover.jpg",
    ],
    features: ["ترکیب استاندارد", "مناسب خرید عمده", "کنترل کیفیت"],
    purchaseType: "direct",
    unit: "کیلوگرم",
    isAvailable: true,
    price: 42000,
    stock: 2500,
  },
  {
    id: 5,
    slug: "concentrate",
    title: "کنسانتره دامی",
    description: "مکمل تغذیه‌ای متعادل برای بهبود رشد و افزایش بهره‌وری دام.",
    longDescription: [
      "کنسانتره با ترکیب متعادل مواد غذایی برای مصرف دام عرضه می‌شود.",
      "مقدار مصرف باید متناسب با برنامه تغذیه مجموعه تعیین شود.",
    ],
    category: "مکمل دام",
    image: "/images/activities/feed.jpg",
    cover: "/images/activities/feed-cover.jpg",
    gallery: [
      "/images/activities/feed.jpg",
      "/images/activities/feed-cover.jpg",
    ],
    features: ["ترکیب متعادل", "بسته‌بندی استاندارد", "مناسب دامداری"],
    purchaseType: "direct",
    unit: "بسته",
    isAvailable: true,
    price: 690000,
    stock: 120,
  },
  {
    id: 6,
    slug: "breeding-semen",
    title: "اسپرم اصلاح نژاد",
    description: "خدمات و محصولات مرتبط با اصلاح نژاد و افزایش بهره‌وری گله.",
    longDescription: [
      "انتخاب مورد مناسب با توجه به شرایط گله و اهداف اصلاح نژادی انجام می‌شود.",
      "ثبت درخواست نیازمند بررسی تخصصی و هماهنگی با مجموعه است.",
    ],
    category: "اصلاح نژاد",
    image: "/images/activities/breeding.jpg",
    cover: "/images/activities/breeding-cover.jpg",
    gallery: [
      "/images/activities/breeding.jpg",
      "/images/activities/breeding-cover.jpg",
    ],
    features: ["مشاوره تخصصی", "انتخاب متناسب با گله", "هماهنگی اجرای خدمات"],
    purchaseType: "request",
    unit: "سرویس",
    isAvailable: true,
    requestFields: {
      quantity: false,
      breed: true,
      approximateWeight: false,
      description: true,
    },
  },
  {
    id: 7,
    slug: "veterinary-service",
    title: "خدمات دامپزشکی",
    description: "معاینه، پایش سلامت و خدمات تخصصی دامپزشکی برای دامداری‌ها.",
    longDescription: [
      "خدمات بر اساس نوع دام، تعداد دام و نیاز مجموعه برنامه‌ریزی می‌شود.",
      "زمان و هزینه نهایی پس از بررسی درخواست اعلام خواهد شد.",
    ],
    category: "خدمات دامپزشکی",
    image: "/images/activities/veterinary.avif",
    cover: "/images/activities/veterinary-cover.avif",
    gallery: [
      "/images/activities/veterinary.avif",
      "/images/activities/veterinary-cover.avif",
    ],
    features: ["معاینه تخصصی", "پایش دوره‌ای", "برنامه پیشگیری و درمان"],
    purchaseType: "request",
    unit: "سرویس",
    isAvailable: true,
    requestFields: {
      quantity: true,
      breed: false,
      approximateWeight: false,
      description: true,
    },
  },
  {
    id: 8,
    slug: "beef",
    title: "گوشت تازه",
    description: "عرضه گوشت تازه با رعایت اصول نگهداری و کنترل کیفیت.",
    longDescription: [
      "محصول با رعایت شرایط بهداشتی و نگهداری مناسب عرضه می‌شود.",
      "قیمت و موجودی نهایی در زمان سفارش قابل بررسی است.",
    ],
    category: "محصولات گوشتی",
    image: "/images/products/livestock.webp",
    cover: "/images/products/livestock.webp",
    gallery: ["/images/products/livestock.webp"],
    features: [
      "کنترل کیفیت",
      "شرایط نگهداری مناسب",
      "امکان سفارش در حجم مختلف",
    ],
    purchaseType: "direct",
    unit: "کیلوگرم",
    isAvailable: false,
    price: 780000,
    stock: 0,
  },
];

export const featuredProducts = products.slice(0, 3);
